const AppActions = {
    SET_BOOKS: "app:SET_BOOKS",
    SET_AUTHORS: "app:SET_AUTHORS",
    DELETE_BOOK_REQUEST: "app:DELETE_BOOK_REQUEST",
    DELETE_BOOK: "app:DELETE_BOOK",
    CREATE_BOOK_REQUEST: "app:CREATE_BOOK_REQUEST",
    CREATE_BOOK: "app:CREATE_BOOK",
    UPDATE_BOOK_REQUEST: "app:UPDATE_BOOK_REQUEST",
    UPDATE_BOOK: "app:UPDATE_BOOK"
};

export default AppActions;